apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rdb-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: rdb-pv
  storageClassName: standard
