FORCE=$1
# Help ...
if [[ $# = 1 && "x$FORCE" != "x-f" ]]; then
     echo "Usage: $0 [-f]"
     echo "    -f: force clean without prompting"
     exit 0
fi
# Real Code
# Prompt if not forced
if [ "x$FORCE" != "x-f" ]; then
    echo 'This will clean all binary files generated by Prutor Compilation'
    echo 'Do you want to continue? [say yes to delete] '
    read prompt
    if [ "x$prompt" != "xyes" ];  then
        echo "Cleanup canceled. Exitting. Bye Bye"
        exit 0;
    fi
    echo "Proceeding with Cleanup."
fi

# If I reached here, it is because of force OR because I said yes to query
docker exec engine1 bash -c 'rm -f /var/www/data/*.out'
